# included to allow the package to be installed in editable mode
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "embed_toolkit"
version = "0.1.1"
# ...
dependencies = [
    "pandas >= 2.2",
]